### ISSUE TITLE
Кнопки Play/Stop

### ISSUE THREAD

**Issue by alexgru** [artpolikarpov/fotorama#1]
Здравствуйте Артём.

Отличная галерея ! Спасибо Вам !
Хотелось бы узнать как можно добавить кнопки Play/Stop и так же если возможно счетчик картинок (3/15)

Ну и если уж совсем ;), то можно ли добавить кнопку для открытия картинки в lightbox , например в prettyphoto - http://www.no-margin-for-errors.com/projects/prettyphoto-jquery-lightbox-clone/

**Comment by tonnyhope** [comment]
This issue was moved to uharbachou/liteGallery#5
