### ISSUE TITLE
Vertical Thumbnails

### ISSUE THREAD

**Issue by ivyowl** [artpolikarpov/fotorama#110]
Hi there,

I really like your gallery and the new responsive features,
i'm just wondering if its possible to have the navigation thumbs display vertically like in the old version?

Many thanks,

Jonny

**Comment by acascon** [comment]
I added vertical thumbs through css, only on desktop and large screens, and not responsive until it goes mobile.
It worked for me. Thanks.

@media screen and (min-width: 1200px) {
.detalle fotorama__nav, .detalle .fotorama__nav--thumbs, .detalle  .fotorama__nav__shaft{ width:100%;}
.detalle .fotorama__nav-wrap{ width:26%; float:left;}
.detalle .fotorama__stage{ width:100%!important; float:right; overflow:visiblea; position:absolute; top:0; left:27%; height:600px!important;}
.detalle .fotorama__stage__shaft, .detalle fotorama__stage__frame{ width:100%!important; }
.detalle .fotorama__stage__shaft fotorama__img{ width:100%;}
.detalle .fotorama__nav__frame--thumb{ display:block; float:none;}
.detalle .fotorama__thumb-border{ display:none!important;}
.detalle .fotorama__active{ opacity:0.2;}
.detalle .fotorama__nav__frame fotorama__nav__frame--thumb{ height: 200px;}
.detalle .fotorama__wrap{ height:600px;}
.detalle .fotorama__nav__frame, .detalle .fotorama__thumb, .detalle .fotorama__thumb img{ width:100%!important; height:137px!important;}
}

**Comment by Abuki121** [comment]
Здравствуйте.. Есть ли метод внедрение fotorama в wordpress на все записи сразу ?
