### ISSUE TITLE
All HTML slides display while fotorama is loading.

### ISSUE THREAD

**Issue by softshape** [artpolikarpov/fotorama#182]
I run fotorama from $(document).ready(). My slideshow type is HTML. While page is loading, I see ALL the slides displayed one under another. Only when document.ready is fired, fotorama script hides all but first slide.

What is the correct setup to display only the first slide during page load? I tried display:none for other slides but it breaks fotorama.

**Comment by Kwadz** [comment]
I have the same issue while I do NOT use `$(document).ready()`.
Is it possible not to display any slides until fotorama is ready to display them properly?
