### ISSUE TITLE
Vertical Thumbnails

### ISSUE THREAD

**Issue by mawz2042** [artpolikarpov/fotorama#184]
why is the vertical thumbnails disabled in the last version? would you be turning the feature on anytime soon? could you let me know?

**Comment by qantus** [comment]
+1 очень ждем

**Comment by dzsm22** [comment]
+1

**Comment by anhskohbo** [comment]
+1

**Comment by w32blaster** [comment]
+1

**Comment by demon101** [comment]
+1

**Comment by s-severin-frontend** [comment]
+1

**Comment by sergey-a-melnikov** [comment]
+1

**Comment by MargoNikk** [comment]
+

**Comment by tatyana-korchemkina** [comment]
+100 Please

**Comment by s-severin-frontend** [comment]
@tatyana-korchemkina Fotorama is unmaintained! :(

**Comment by demon101** [comment]
@artpolikarpov  есть ли возможность разработки этой фичи за оплату?

**Comment by guz-anton** [comment]
Please, take a look on Magento 2 enhancmets:
 https://github.com/magento/magento2/tree/2.2-develop/lib/web/mage/gallery

**Comment by artpolikarpov** [comment]
Sory, that option won't come back.
