### ISSUE TITLE
Событие load для превьюшек

### ISSUE THREAD

**Issue by vitkarpov** [artpolikarpov/fotorama#196]
Как узнать когда превьюшки окажутся в доме?

На `f:ready` их еще нет, а `f:load` отрабатывает при загрузке оригинального, большого изображения.

Это может быть полезно, когда хочется добавить кастомной логики превьюшкам. 

Например, требуется положить рядом еще по картинке с `filter: grayscale`, чтобы сделать эффект появления цвета при наведении.

**Comment by vitkarpov** [comment]
@artpolikarpov привет спустя 5 лет 😉

**Comment by artpolikarpov** [comment]
Привет :)
