### ISSUE TITLE
Fotorama Callbacks?

### ISSUE THREAD

**Issue by macsupport** [artpolikarpov/fotorama#2]
Great plugin! I was wondering when you might be including your API docs? I am interested in callbacks for fotorama. I want to use Font awesome icons instead of the png for navigation/video and I am appending some code to do this:

```
 $('.fotorama__arr--next .fotorama__arr__arr').append('<i class="icon-chevron-sign-right icon-3x"></i>').addClass('shadow');
 $('.fotorama__arr--prev .fotorama__arr__arr').append('<i class="icon-chevron-sign-left icon-3x"></i>').addClass('shadow');
$('.fotorama__fullscreen-icon').append('<i class="icon-resize-full icon-2x"></i>').addClass('shadow');
 $('.fotorama__video-play').append('<i class="icon-youtube-play icon-4x"></i>').addClass('shadow');
 $('.fotorama__video-close').append('<i class="icon-remove-circle icon-3x"></i>').addClass('shadow');

```

 It works well for everything but the video play icon. I find I lose the video play icon unless the image for the video is showing and after calling full screen. I'm thinking adding it as a callback will work better in this case.
BTW, it works well with HTML5 video as well.
[Demo with font icons](http://www.macosxsupport.com/fotorama)

**Comment by tonnyhope** [comment]
This issue was moved to uharbachou/liteGallery#6
