### ISSUE TITLE
Is it possible to dynamically show items?

### ISSUE THREAD

**Issue by glebcha** [artpolikarpov/fotorama#210]
The main idea is to show number of items in row depending on it's sizes in @media.
Here you can see what am I talking about http://www.owlgraphic.com/owlcarousel/demos/custom.html

Any ideas are highly appreciated because I love fotorama so much that don't want to use anything else.

**Comment by yhwhdesign** [comment]
We are dynamically showing items. check this out and let me know if it is what you are talking about...

We do not list the images in the html, we are pulling data from a database and using django code to pull them out of the db, and putting them plus the data we need from the database into the html.

http://www.arkansasonline.com/galleries (select a gallery when you get there)
