### ISSUE TITLE
Append Browser Compatibility Levels to README

### ISSUE THREAD

**Issue by X4** [artpolikarpov/fotorama#233]
Hi,

it would be greatly useful to know which Browsers are compatible with fotorama. It seems that it's not compatible with <= IE9, but I may be wrong..

**Comment by mohammedkhan** [comment]
Hi, this is kind of old, but I've just implemented fotorama and can confirm it's not working in IE9, but is in 11, I'm yet to try 10. I'm using it inside the bootstrap framework if that makes a difference. The initial image loads, but then it switches to the throbber.

**Comment by mohammedkhan** [comment]
Twitter Bootstrap also supplies a photo carousel similar to fotorama, just saw this in their documentation:
"Transition animations not supported in Internet Explorer 8 & 9
Bootstrap exclusively uses CSS3 for its animations, but Internet Explorer 8 & 9 don't support the necessary CSS properties. Thus, there are no slide transition animations when using these browsers. We have intentionally decided not to include jQuery-based fallbacks for the transitions."
