### ISSUE TITLE
Full photo size while specifying thumbs

### ISSUE THREAD

**Issue by skwp** [artpolikarpov/fotorama#237]
It seems like there are two mutually exclusive options. Either this:

``` html
<a href="full image url">
   <img src="thumb goes here">
```

or this

``` html
   <img src="regular size" data-full="full size">
```

In the second variant there is no way to use thumbnail specifications. I'm trying to have 3 image sizes (thumb, on page, and full screen). Does fotorama support this? Every time I try to add `data-full` onto the example with thumbnails, it does not respect it in the full screen view.

**Comment by kraiz** [comment]
Stumbled over this, too. Thought i found a broken feature combination.
In the last hope i searched the issues for "data-full" and found this one. 

I really like to contribute this missing info to the docs, but it's not hosted on github, right?
