### ISSUE TITLE
Вариант отмены FullScreen для мобильных устройств

### ISSUE THREAD

**Issue by AndreyLadniy** [artpolikarpov/fotorama#241]
Возможно ли добавить отмену FullScreen по перемещению "пальцем" сверху вниз, так же как при native Fullscreen. Просмотр удобный, а вот для отмены попадать в стрелочки, если еще они и спрятались - немного не удобно.
Еще вариант - back button. Руки так и тянутся нажать ее в полноэкранном режиме, но в результате переход на страницу назад. Но на сколько это правильно?

**Comment by artpolikarpov** [comment]
#313 об этом
