### ISSUE TITLE
package.json incomplete

### ISSUE THREAD

**Issue by feeela** [artpolikarpov/fotorama#242]
The package.json file seems to be incomplete. I've made some changes and will push them to a branch named after the number of this issue.
### Missing Dependencies

The following grunt-packages are used but not named as dependency. I've added those with the most recent version number – which is probably to high.
- grunt-contrib-copy (~0.5.0)
- grunt-contrib-sass (~0.7.3)
- grunt-contrib-clean (~0.5.0)
### npm WARN: No repository field.

I've added this setting to the package.json with the URL of this repository here.
See also: https://www.npmjs.org/doc/json.html#repository

**Comment by nikbelikov** [comment]
Hi!
Your slider is in npm, but does not working with browserify.

**Comment by feeela** [comment]
@nikbelikov How does that comment relate to this issue? Also, what does "not work" mean?

**Comment by nikbelikov** [comment]
I guess, there is no "main" property in the package.json. Try to use plugin with Browserify to understand what I mean.

**Comment by wasd171** [comment]
I've manually added `"main": "fotorama.js"` line to `package.json`, but I get `Uncaught Fotorama requires jQuery 1.8 or later and will not run without it.` error. I'm using browserify and require jQ and fotorama as
```
$ = require 'jquery'
fotorama 	= require 'fotorama'
```
