### ISSUE TITLE
android 2.3 fallback

### ISSUE THREAD

**Issue by scooterlord** [artpolikarpov/fotorama#271]
Hello, I thought I'd ask if there's some kind of fallback for older android devices.

Entering fotorama.io site with an old 2.3 android version = instant crash. Are there any plans for support of these devices? or any other kind of fallback? Devices are not that old, so it would really be a good thing to support them!

Thanks!

**Comment by boynet** [comment]
just tested on android 2.2 default browser and it working, so maybe it 2.3 specific bug

**Comment by scooterlord** [comment]
thanks for the reply! If you are given any chance to test on 2.3 please let me know. I am still working on the project, so this has come to second priority atm but it's still very important!
