### ISSUE TITLE
Fotorama in Ghost

### ISSUE THREAD

**Issue by WillemDeGroef** [artpolikarpov/fotorama#304]
Just to let you know that fotorama is very easy to plug in into the Ghost blogging platform:

![screen shot 2014-09-13 at 12 55 02](https://cloud.githubusercontent.com/assets/3964753/4260306/fa73dc00-3b34-11e4-96d0-f4f677c437e9.png)

I like it especially because you can still use the `insert image` feature from Ghost.
If one adds the required files in the theme, it basically comes down to add `<div class="fotorama">` and `</div>` in your post to enjoy the beauty of fotorama!

**Comment by itdansharpe** [comment]
Just found this article after making a tutorial for it! Love how simple the integration is!

http://dansharpe.com/ghost-blog-fotorama
