### ISSUE TITLE
Image vertical stretching - not cool

### ISSUE THREAD

**Issue by tmkpl** [artpolikarpov/fotorama#312]
First of all, thank you for your hard work on this code. It is very useful and modern gallery. I've been using it recently, and I think I've encountered a glitch.
It seems that fotorama code stretches images vertically by 1 pixel, if the image horizontal size is bigger than vertical size. It looks like "off by one" programming error.

Please see the following example http://ow.ly/CiIqn

I know it's not a big issue, but sometimes you want to achieve 'per pixel' sharpness, and you can't.
I've prepared images for my website, did some sharpening in PS so they would look nice, but they're blurred in fotorama by this 1 pixel stretching.

I would be very appreciated, if someone could fix it.
This was tested in Chrome 37, Firefox 32 and IE 11.

**Comment by artpolikarpov** [comment]
Try the [4.6.3](https://github.com/artpolikarpov/fotorama/releases/tag/4.6.3)?
