### ISSUE TITLE
Wrap images with links

### ISSUE THREAD

**Issue by ravinggenius** [artpolikarpov/fotorama#322]
I'd like to have each image link to an arbitrary page when clicked (instead of advancing to the next slide or pausing the slideshow). Wrapping each image in a link doesn't work:

``` html
<a class="banner" href="http://wherever.com/"><img alt="collaboration" src="assets/images/banners/banner1.jpg" /></a>
```

I also tried adding `data-href` and `data-link` attributes to the images, but that didn't work either.

**Comment by Doctorrr** [comment]
I'm using this way of inserting images as separate HTML tags:

`
<div class="slider_fotorama fotorama"
     data-allowfullscreen="false"
     data-click="false"
     data-loop="true"
     data-auto="true"
     data-autoplay="3000"
     data-shuffle="true"
     data-arrows="true"
     data-width="100%"
     data-fit="contain"
>


    <div data-img="https://s.fotorama.io/1.jpg">
        <div class="slider_inner">
            <a href="#/111111"><img src="https://s.fotorama.io/1.jpg" style="width:100%;"></a>
        </div>
    </div>

    <div data-img="https://s.fotorama.io/2.jpg">
        <div class="slider_inner">
            <a href="#/222222"><img src="https://s.fotorama.io/2.jpg" style="width:100%;opacity: 50%;"></a>
        </div>
    </div>

</div>
`
