### ISSUE TITLE
slideshow autoplay interval corrupts on mousemove

### ISSUE THREAD

**Issue by mjau-mjau** [artpolikarpov/fotorama#323]
I have no idea why this is happening, but the autoplay interval extends itself somehow when moving mouse pointer. You can see it happen here:
http://mjau-mjau.com/concepts/slideshow/inline/

Click the play button, and if you **don't** move the mouse, autoplay works nicely and intervals are correct. If you **do** move the mouse between slides, somehow it extends the interval and messes up the autoplay. I have no clue why mousemove effects the autoplay/interval.

**Comment by artpolikarpov** [comment]
Done in the [4.6.3](https://github.com/artpolikarpov/fotorama/releases/tag/4.6.3) :)
