### ISSUE TITLE
Auto-Hide Thumbs in Fullscreen Mode (wordpress version)

### ISSUE THREAD

**Issue by enone** [artpolikarpov/fotorama#335]
Hi All,

I've Not Fount A Way/Parameter To Auto-Hide The Thumbinails When The User Switch To Full Screen Mode...

Is It Possible? I've Found That Can Be Done In The HTML Version But I'm Unable To Understand 
Where I Can Make These Changes In The Wordpress Version Since The .js Is Protected...

It Will Be Nice To Have A Value In fotoramaDefaults.js Config File Like: auto-hide-tumb: true / false / fullscreen

Later...
enone

**Comment by inreti** [comment]
I solved this (same issue in #422). Quite easy, if you once know how to do it. The trick is to use the events! The following script should do the trick for every fotorama container:

```js
$('.fotorama').each(function() {
        $(this).on('fotorama:fullscreenenter', function(e, fotorama) {
            fotorama.setOptions({
                nav: false,
            });
        });
        
        $(this).on('fotorama:fullscreenexit', function(e, fotorama) {
            fotorama.setOptions({
                nav: 'thumbs',
            });
        });
});
```
