### ISSUE TITLE
Bootstrap 3 и box-sizing: content-box

### ISSUE THREAD

**Issue by Gurylev** [artpolikarpov/fotorama#339]
Я вывожу внутри фоторамы вёрстку bootstrap, у которой как в foundation #31 box-sizing должен быть в значении border-box.
Из-за .fotorama__wrap * {box-sizing: content-box} приходится переназначать .fotorama__html * {box-sizing: content-box !important}
От этого хочется от этого избавиться. Да и без бутстрапа я использую тоже самое обнуление.

Отсюда просьба: 
Сделай, пожалуйста, content-box не для *, а именно для тех дивов, которым это нужно.

**Comment by artpolikarpov** [comment]
Done in the [4.6.3](https://github.com/artpolikarpov/fotorama/releases/tag/4.6.3) :)
