### ISSUE TITLE
YouTube video starts from beginning on window resize

### ISSUE THREAD

**Issue by nazar-pc** [artpolikarpov/fotorama#348]

**Comment by nazar-pc** [comment]
Why are you closing issues and PRs without any explanation?

**Comment by artpolikarpov** [comment]
It's been years, I didn't think anyone else was waiting for answers. 

To be specific about this issue, I couldn't reproduce this bug — resizing the browser does not break video player.

In general, version 4 will not be developed anymore. Next version should be written from scratch.

**Comment by nazar-pc** [comment]
Thanks, nice to hear next version is coming
