### ISSUE TITLE
console is undefined

### ISSUE THREAD

**Issue by labordus** [artpolikarpov/fotorama#349]
Hi,
I'm sourcing fotorama from http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.3/fotorama.js

IE7 & IE8 have issues with console for some reason.. it hangs or gives some message about console.log being undefined.
For now I  Commented out "console.log('fit') and everything seems to work fine.
Because of this I have to distribute fotorama.js with my application, I'd rather dont..
Is there some better way of dealing with this?
Thanks, Mark.

**Comment by mbardelmeijer** [comment]
Related: #347
