### ISSUE TITLE
Is fotorama-defaults.js still working?

### ISSUE THREAD

**Issue by alexandreracine** [artpolikarpov/fotorama#358]
Hi,

WP version 3.5.1 , fotorama Version 4.6.3 

I am using the file fotorama-defaults.js to store my preferences , but it seems that it is not working since...?? I don't know when. The autoplay does not start for example here http://www.marimage.ca/mariage/

Content of the file.

jQuery.Fotorama.defaults = {
  allowFullScreen: false,
  autoplay: 3000,
  loop: true,
  keyboard: true,
  transition: 'crossfade',
  transitionDuration: 1500
}

Thanks

**Comment by h8every1** [comment]
You sholud use global variable `fotoramaDefaults` not `jQuery.Fotorama.defaults`.
