### ISSUE TITLE
Bug on z-index (?) with Webkit

### ISSUE THREAD

**Issue by ghost** [artpolikarpov/fotorama#369]
Hi,

I use the 4.6.3 version and I have a bug with Webkit. I've identified that the bug provides from js file and not from css files. For example, see http://snrb.simplicicom.fr/ (it's a demo site) on a smarphone or resize the browser window to have the size of a smartphone, and open the menu.

With Firefox, the menu is over it of the slider, but with Chrome (Webkit), the menu is under the slider.

I used autoprefixer to ensure that the CSS are rights.

If the js file is deactivate, the bug is removed.

I hope this can help you.

Sébastien.

**Comment by eonshao** [comment]
Hey!

It's not a bug!!

In my case, it's the normal behavior for Chrome and its brothers...

See that : https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context

Have a good day!
