### ISSUE TITLE
More options for Captions

### ISSUE THREAD

**Issue by randomfreeform** [artpolikarpov/fotorama#373]
Great plugin for WP... But why oh why have captions on top of images?! 
That's ugly as can be... put them under or to the side.. please.
Also, let us put any html in there we like. 
Could be cool.
THANKS for listening.
R

**Comment by orzechow** [comment]
I agree, there should be an option to put the captions below the image.
Right now it's not easily possible, because the caption box overflows when set outside the box by CSS.

**Comment by andrearicci** [comment]
I did put the text under the image - it required CSS editing wich I can't remember 8that was years ago). 
You're welcome to check the code used here: https://ellynagaoka.it
