### ISSUE TITLE
fotorama.destroy() does not reset image size of fotorama.

### ISSUE THREAD

**Issue by radry** [artpolikarpov/fotorama#379]
1) Load images with javascript into fotorama, (dynamic) size is correct for the first shown image.
2) destroy instance with fotorama.destroy()
3) load new images with a different image size (for example larger) with javascript
fit is set to default.

Result: The size of fotorama is the same as the first image set. That means if the images where smaller then the second set is scaled down to that first size instead of using the available space defined by maxwidth or maxheight.

Expected result: The size is reset and adjusted according to the new image set as if the website was reloaed.

When reloading the page and loading the second (larger) image set before the first set, the size is correct. The issue only occurs when loading and destroying image sets wihout reloading the website.

**Comment by jaswinder97** [comment]
After pushing the images to the fotorama object,try to reset its frame size as:

$.each(previews,function(index, url){
   fotorama.push(JSON.parse(url));
});

fotorama.resize({
    width: 700,
    height: 500
  });

This will not break the UI even you destroy it again and reinitialise using ajax.
