### ISSUE TITLE
Почему fotorama:load срабатывает 2-3 раза

### ISSUE THREAD

**Issue by g-ilham** [artpolikarpov/fotorama#384]
Привет,
 при кастомизации под свою логику у меня обнаружились следующие проблемы/вопросы:
При загрузке страницы, ивент `fotorama:load` срабатывает два раза:
![Image of calback](http://cs623931.vk.me/v623931375/21ca5/Gjq74Sbh5kE.jpg)

А когда жмешь на thumbnail, который находится через 2 и больше thumbnail-ов, то ивент `fotorama:load` срабатывает 3 раза и  `fotorama:show` и  `fotorama:showend` ивенты не отдают текущий фрейм:
![Image of calback](http://cs623931.vk.me/v623931375/21cb8/pcLYXkmh4Eo.jpg) 

Это заложено в логику фоторамы либо я что-то не так делаю?
Спасибо. :beers:

**Comment by bender-r** [comment]
Сегодня столкнулся с такой же трудностью. Но я вышел из ситуации используя fotorama:show
Текущий фрейм, к примеру - путь fotorama.activeFrame.img мне нормально отдает. Версия фоторамы 4.6.3

Как я понял, при использовнии fotorama:load фоторама пробует подтягивать предыдущий и следущий фреймы, поэтому срабатывает 3 раза. Это на сколько помню сделано с целью ускорения загрузки. Ну и само собой если первый или последний фрейм, событие срабатывает 2 раза

**Comment by yoime** [comment]
@g-ilham 
'fotorama:load ' +            // Stage image of some frame is loaded
в stage фоторамы всегда 3 блока - превью, и ее ближайшие картинки
если выбирать через 2 и более, то несколько раз и дернется ивент

**Comment by yoime** [comment]
@bender-r 
да, и на сколько я вижу, для слайдовой анимации также

**Comment by g-ilham** [comment]
@yoime понятно, спасибо :beers:
