### ISSUE TITLE
modernizr dependencie collides with newer modernizr usage

### ISSUE THREAD

**Issue by pgr1973** [artpolikarpov/fotorama#392]
Hi Artem,

using the latest version of modernizr.js collides with fotorama.js, which makes it impossible to use the plugin in contexts, which require other modernizr features than "CSS 3D Transforms".

Do you plan (or even have in queue) a fotorama-version which is usable independly from other modernizr versions?

Regards Paddy

**Comment by zxqfox** [comment]
:+1: to move this out into bower dependencies.

**Comment by fedotxxl** [comment]
+1. It should be as dependency (similar to jquery)
