### ISSUE TITLE
Fotorama и W3C

### ISSUE THREAD

**Issue by fogrew** [artpolikarpov/fotorama#394]
W3C валидатор ругается, что фоторама добавляет атрибут disabled к div role="button"

![image](https://cloud.githubusercontent.com/assets/484159/6917748/3e4ee3c6-d7b0-11e4-90b5-ece3d73f4b57.png)

```
<div class="fotorama__arr fotorama__arr--prev fotorama__arr--disabled" tabindex="-1" role="button" disabled="disabled"></div>
```

И ещё фоторама добавляет в документ инлайн-стили и добавляет их сразу перед фоторамой. 
![image](https://cloud.githubusercontent.com/assets/484159/6917762/5cea775a-d7b0-11e4-9c04-e1fef39b6a47.png)
Поскольку стили всё равно работают в глобальном контексте, следует добавлять их в head.

Ведь не только я договорился с клиентом, что документ будет проходить валидацию. Это же выгодно для seo. И неизвестно, в какой момент роботы проверяют документ, ибо выполнять скрипты и имитировать запуск страницы они уже умеют.

**Comment by korobochkin** [comment]
лол

**Comment by uharbachou** [comment]
Суть того, что стили в блоке вставлены для более простого управления ими.
