### ISSUE TITLE
Let's make fotorama BEM-block? / RU: Сделаем из фоторамы BEM-блок?

### ISSUE THREAD

**Issue by zxqfox** [artpolikarpov/fotorama#396]
What we'll get:
- Nothing more except used (build will contain just needed code);
- Link between js & css (blocks and elements will have docs at the same place with code);
- Possibility to make specs and template specs placed about core and docs;
- Possibility to have files for few template engines (with no afraid of broking something);
- `bower` as package manager (e.g., to install and update modernizr);
- And, as a result, possibility to build as many different versions of fotorama as we need out of the box, clearly, without hacks, including Modernizr, and the rest (as it happens now) using just one configuration file for `enb`;
- Bonus: a lot of folks who doesn't understand how to start contributing just because code base is huge and monolithic.

With that:
- Public API won't change (or will change insensibly);
- We will split block (it's already splitted a little, btw) to functional parts — elements, to not include code that we don't need to work, also we split modifiers to separate files and define dependencies for them — any excessive code will we moved out because we'll start see it;
- We'll use `enb` just to have work correctly with dependencies and run tests with one-liner out of the box;
- If possible we'll move out the rest 3rd party and excessive code, e.g. make some issues in Modernizr (if we need something);

Thoughts?

---

RU:

Что получим:
- Ничего лишнего в сборке (собираться будет только нужное);
- Связь js и css (блоки и элементы будут иметь свою документацию рядом с кодом и стилями);
- Возможнось писать тесты на логику и шаблоны, и складывать их рядом с кодом и стилями;
- Возможность иметь несколько различных шаблонизаторов (без страха что-то сломать);
- Подтянем bower как менеджер библиотек (чтобы стягивать и обновлять modernizr, например);
- И, как итог, возможность собирать дополнительные (полные) сборки из коробки, наглядно, без хаков, включая Modernizr, и остальное (как происходит сейчас) с помощью одного конфига для `enb`;
- Бонусом: кучу контрибьюторов, которые не знают как подойти к станку, потому что код велик и монолитен.

При этом:
- Публичное API не изменится (либо изменится крайне мало);
- Разделим блок (он и так уже поделен, на самом деле) на составные части — элементы, чтобы не подключать лишнее при желании, модификаторы тоже разнесем по файлам и четко пропишем зависимости — все лишнее автоматически постепенно уедет;
- Собирать будем не grant'ом (или не только грантом), но еще и enb (чтобы более плавно работать с зависимостями и иметь возможность стартовать тесты из коробки);
- По возможности унесем весь посторонний код из проекта и заведем issues в Modernizr (если чего-то не хватает);

Что думаете?

**Comment by h4** [comment]
И вместо простого и понятного подключения получим бем-тулз, игрек-модулес и вот этот вот всё?

**Comment by zxqfox** [comment]
@h4 Получим все то же самое, что есть и сейчас. ENB != ymodules и бем-тулз.

**Comment by h4** [comment]
@zxqfox Сейчас это библиотека вида «подключи два скрипта — и вперёд». А вы предлагаете примотать сюда две технологии с порогов входа выше чем у Vim.

**Comment by zxqfox** [comment]
@h4 Я уже не знаю, что я предлагаю. Изначально я предлагал всего лишь структурировать код и https://github.com/artpolikarpov/fotorama/blob/master/Gruntfile.js#L9-L32 использовать enb или что-то такое, чтобы не хранить зависимости внутри мейк файла.

Ибо это тупо неудобно.
