### ISSUE TITLE
Можно не пропускать "битые" изображения?

### ISSUE THREAD

**Issue by andruxa-nn** [artpolikarpov/fotorama#402]
Сделайте пожалуйста возможность настраивать Фотораму, чтобы она не пропускала "битые" изображения, а полностью отрабатывала все стандартные события и например показывала какую-либо иконку.

**Comment by ulaharbmg** [comment]
забавно, что значит битые?
если 404, то картинки там не будет. за качество картинки отвечаете Вы.
