### ISSUE TITLE
Syntax error in fotorama.io

### ISSUE THREAD

**Issue by networksolution** [artpolikarpov/fotorama#403]
Hi. I'd like to point out an error at page http://fotorama.io/set-up/
You aren't closing link and img tags properly.

**Comment by maximal** [comment]
HTML is not so strict as XML/XHTML.
HTML5 allows you not to close short tags, such as `<br>`, `<hr>`, `<img>`, `<link>`, `<meta>` and others.

Anyway, I personally prefer closing of all tags.
