### ISSUE TITLE
ng-click not working on mobile device

### ISSUE THREAD

**Issue by wodka** [artpolikarpov/fotorama#404]
Hi, 

it is not working to have an ng-click (hm-tap does not even work on desktops) in the description of a slide.

is there some way to allow the touch events to propagate?

br Michi

**Comment by beshur** [comment]
Have same issue (not `ng-click`, but just clicks are not working on the slide description).

Have you found any solution, @wodka ?

**Comment by wodka** [comment]
@beshur what I use right now is hm-tap on the main div.

```html
<div ui-jq="fotorama" hm-tap="sliderClick($event)">
  <div ng-repeat="slideIdx,slide in slides" data-idx="{{slideIdx}}" data-img="{{slide.image}}">
  </div>
</div>
```

```javascript
$scope.slides = [
  {img:"",other:""},
  {img:"",other:""},
  {img:"",other:""}
];

$scope.sliderClick = function(event) {
  var e = angular.element(event.target);
  var f = angular.element('#fotorama').data('fotorama');

  if (
    e.hasClass('fotorama__html')
    && f.activeFrame.idx
  ) {
    var slide = $scope.slides[f.activeFrame.idx];

    // TODO use your slide for whatever you want
  }
}
```

hope this helps

**Comment by beshur** [comment]
@wodka, actually my problem was fixed when I changed `span` to `a`, and did not have time to go deeper. Guess there can be some tag-specific event.
