### ISSUE TITLE
Вертикальные изображения переворачиваются на планшетах

### ISSUE THREAD

**Issue by maximal** [artpolikarpov/fotorama#405]
Скрины с _Айпад Эйр_:
- https://trello-attachments.s3.amazonaws.com/554a22af92af026d8cc76723/800x600/fe0766ac51a2bf2aa64e91ebdec276b3/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD_1.jpg
- https://trello-attachments.s3.amazonaws.com/554a22af92af026d8cc76723/800x600/80d3581267df61b59b67fa3978db9107/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD_2.jpg

Ссылка для проверки: http://fonar.tv/photorep/2015/05/23/posledniy-zvonok-2015-goda-v-belgorode-i-rzhevke#image-126-40 (вертикальные изображения там ближе к концу).

На _Айфоне_ с _Сафари_ тоже самое.

На планшете _Престижио_ нормально, на телефонах-андроидах тоже.
Похоже, только с Эпплобраузерами проблема.

**Comment by maximal** [comment]
И да, я там в конце файла http://fonar.tv/static/js/app.js написал код для того, чтобы можно было на конкретную фотку давать ссылку (опция `hash` не совсем так работает, как хотелось бы). Хотел бы узнать, правильно ли написано. Иногда, если много фоторам на странице, они не успевают загрузиться, и нужная фотка не показывается, поэтому надо ждать её загрузку:

```js
// Делаем ссылку на конкретное изображение
$('.fotorama')
	// При входе в полноэкранный режим, включаем `hash`
	.on('fotorama:fullscreenenter', function (e, fotorama) {
		fotorama.setOptions({
			hash: true
		});

		if (window.location.hash !== ('#' + fotorama.activeFrame.id)) {
			window.location.hash = fotorama.activeFrame.id;
		}
	})
	// При выходе в полноэкранный режим, выключаем `hash`
	.on('fotorama:fullscreenexit', function (e, fotorama) {
		fotorama.setOptions({
			hash: false
		});
		window.location.hash = 'fonar';
	});

if (location.hash.length > 0) {
	// Если есть хеш, похожий на ссылку на фотку
	//scrollTo(location.hash);
	var match = location.hash.match(/^#image\-(\d+)\-(\d+)$/);
	if (match) {
		// Ждём, пока фоторама загрузится и показываем нужную фотку
		$('#gallery-' + match[1]).on('fotorama:ready', function (e, fotorama) {
			fotorama.show(parseInt(match[2]));
			fotorama.requestFullScreen();
		});
	}
}
```

**Comment by andreyvolokitin** [comment]
Похоже на это влияет EXIF файла: http://stackoverflow.com/questions/21201548/how-to-prevent-auto-rotating-images-on-ios-on-html-with-css-javascript/21465242#21465242. Пересохранил картинку через Save for the web и картинка перестала крутиться.
