### ISSUE TITLE
reduce swipe sensitivity on fullscreen

### ISSUE THREAD

**Issue by plegall** [artpolikarpov/fotorama#408]
Hi,

On fullscreen (and only on fullscreen) the swipe is very sensitive. I mean that a very small (in pixels) swipe goes to the prev/next image.

I have implemented a swipe up/down for other features (photo selection add/remove) but if the swipe left/right is too sensitive like now, the swipe up/down nearly always implies a swipe left/right.

Is it possible to have a less sensitive swipe left/right?

Thank you for your help :-)

**Comment by mistic100** [comment]
I came with a dirty solution consisting of always setting `stageShaftTouchTail.snap` to 0
https://github.com/artpolikarpov/fotorama/blob/acfdf0d1353eae7f1b6a0888a5d9d5fda305ab7c/src/js/fotorama.js#L382

It appears to really loosen the sensitivity without disabling swipe/click-drag.
