### ISSUE TITLE
doesn't work with pagespeed module

### ISSUE THREAD

**Issue by ConfusedVorlon** [artpolikarpov/fotorama#415]
this can be avoided by disallowing pagespeed from using fotorama with:

pagespeed Disallow "*/fotorama.css";

I'm not sure how common this issue is - but it might be worth adding to the docs somewhere

thanks for a great project.

**Comment by joshuataylor** [comment]
Works fine with the pagespeed module for me? Both JS/CSS don't need to be excluded for it to work for me.

**Comment by ConfusedVorlon** [comment]
that's odd. Are you using the combine_css filter?

disabling that filter allowed things to work for me.

the docs mention 'This filter is considered low risk. However, JavaScript can be written that walks the DOM looking for <link> entries with certain syntax. Such JavaScript may behave differently on a page which has modified CSS links in this way.' which I had assumed to be the problem.
