### ISSUE TITLE
Carousel by fotorama

### ISSUE THREAD

**Issue by demon101** [artpolikarpov/fotorama#420]
It will be very usefull, if fotorama will support carousel feature. Something like http://demo.dev7studios.com/caroufredsel/

It's can be Thumbnails but with fullsize picture only by fullscreen view

**Comment by demon101** [comment]
like this http://stackoverflow.com/questions/19242733/fotorama-4-slide-more-than-1-image

**Comment by kattiperk** [comment]
Are any changes on this issue?
@demon101 , could you notify me if you have some ideas about that?
mail - kattiperk@gmail.com or skype - zizzazza
