### ISSUE TITLE
Fotorama does not load

### ISSUE THREAD

**Issue by miraclebg** [artpolikarpov/fotorama#421]
Hello there,

Because i am not used to working with GitHub yet i am not certain on how to propose a fix - so i am writing a manual support issue - hope that's fine! :)

I am working on a site which includes html minification. After applying it - fotorama refuses to load.

I've cloned the repo and started testing around the raw source.

The problem lies in the src/js/utils.js file at line 272:

 } else if (!$this.is(':empty')) {

This does not match after the minification process passes.

Here is an excerpt of how it looks in html:

`<ul><li><p class="key"></p>тел:<p class="val">0887 237 839</p><li><p class="key"></p>тел:<p class="val">0887 213 099</p><li><p class="key"></p>e-mail:<p class="val"><a href=“mailto:ispdd@ispdd.com”>ispdd@ispdd.com</a></p></ul></aside></div></div></div></div></div><div id="pre_main_area"><div id="main_content_area"><div class="container"><div class="single-project"><div class="row"><div class="col-lg-12"><div class="gallery-holder"><div class="gallery"
data-keyboard="false"
data-width="100%"
data-height="600"
data-thumbwidth="112"
data-autoplay="true"
data-loop="true"
data-fit="contain"
data-transition="slide"
data-clicktransition="crossfade"
data-thumbheight="71"
data-allowfullscreen="true"
data-nav="thumbs"><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-9593446-5430035510.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-9593446-5430035510.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-1476463-9034332837.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-1476463-9034332837.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-5992564-4119562935.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-5992564-4119562935.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-9593446-8277179711.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-9593446-8277179711.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-1476463-1186081683.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-1476463-1186081683.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-5992564-7436407340.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-5992564-7436407340.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-2742316-6247997530.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-2742316-6247997530.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-7504352-9027842754.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-7504352-9027842754.jpg"
class="item"></div><div data-img="http://ispdd.miracle.com/media/projects/big/proekt-za-kashta-Bistritza-8203834-6770187607.jpg" data-caption="Еднофамилна къща" data-thumb="http://ispdd.miracle.com/media/projects/thumb/proekt-za-kashta-Bistritza-8203834-6770187607.jpg"
class="item"></div></div></div></div></div><div class="row"><div class="single-project-cont"><div class="col-lg-4"><div class="row"><div class="col-lg-12"><div class="share-box"><div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>`

**Comment by ulaharbmg** [comment]
Hi,
is this HTML valid? as i see it look like 
```html
<ul>
</a>
```

**Comment by miraclebg** [comment]
Hi there,

Yes - it’s valid.

BUT - certain optimizations have been applied to it as i mention - for HTML minification purposes.

The issue you are referring below is due to removing the ending tags of certain tags: option, li, dt, dd, tr, th, td as it is allowed by html5 specs:

http://www.w3.org/TR/html5/syntax.html#syntax-tag-omission


That is not the problem - i tried disabling this and it’s still the same.

Attaching the actual full source code of the page which prevents fotorama to appear.

Also attaching the fotorama js which was modified (look for ISPDD):





Thanks!
___________________________________
Martin Kovachev - IT Manager,
Nimasystems Ltd
Tel.: +359 896 610 876
Fax: +359 32 395 283
Skype: miracle_bg
E-Mail: miracle@nimasystems.com
Website: http://www.nimasystems.com
