### ISSUE TITLE
Show thumbs only in fullscreen mode

### ISSUE THREAD

**Issue by wuuti** [artpolikarpov/fotorama#422]
I am looking for a way to show the thumbnails only in fullscreen mode. When not beeing in fullscreen mode, no navigation (neither dots nor thumbs) should be visible. (this way I can have a slidable cover in small and a fullscreen with overview of thumbs).
Is it possible currently? Could manage to get that working. If not, this would be a useful enhancement.

**Comment by ulaharbmg** [comment]
fotorama fired events
```javascript
'fotorama:fullscreenenter ' + // Fotorama is fullscreened
'fotorama:fullscreenexit ' +  // Fotorama is unfullscreened
```
Use api setOptions can customize navigation
