### ISSUE TITLE
Slideshow image flickering in IE 11 / Windows 8.1

### ISSUE THREAD

**Issue by b00nish** [artpolikarpov/fotorama#429]
Hello

When using the fotorama slideshow with Internet Explorer 11 under Windows 8.1, there are images flickering at the right side of the slideshow.

See: http://strategyplayer.net/wobau/

Other browsers work fine.

How can I resolve this?

**Comment by OscarDeDios** [comment]
I have the same problem in IE11. 

To see another example: the web site of Fotorama: http://fotorama.io/customize/thumbnails/

Please help.

Thanks.

**Comment by OscarDeDios** [comment]
This is very annoying.

I've change the next CSS to hide the flickering, but the slide effect in IE11 doesn't work fine. (in chrome ok):

.fotorama__wrap--css3 .fotorama__html,.fotorama__wrap--css3 .fotorama__stage .fotorama__img
 {
 	transition-property:opacity;
 	transition-timing-function:linear;
 	transition-duration: 1ms;  //previous value = 0.3s
 }

The flickering effect was this 0.3 seconds, if you change to something like 2 seconds you will see the image this time. 

If you fix this properly it would be great artpoli.

Thanks.

**Comment by b00nish** [comment]
Any news on this issue?

**Comment by b00nish** [comment]
Has the development / bugfixing of fotorame been abandoned?

**Comment by mbardelmeijer** [comment]
Any update on this?

**Comment by b00nish** [comment]
@mbardelmeijer 

The workaround that @OscarDeDios provided works okay for me.

But I think @artpolikarpov has stopped providing bugfixes for fotoroma. Otherwise there would have been a reaction on this issue that has been reported 8 months ago.

**Comment by mbardelmeijer** [comment]
@b00nish Thanks, yes the workaround from @OscarDeDios works fine! Thought this issue could be fixed upstream, but you're right, project seems dead unfortunately.

**Comment by DsXack** [comment]
@OscarDeDios works fine for me! Thanks!

**Comment by esemlabel** [comment]
Try this:
```
.fotorama__stage .fotorama__loaded--img:not(.fotorama__active):not(.fotorama__fade-front):not(.fotorama__fade-rear) {
    opacity: 0 !important;
}
```
