### ISSUE TITLE
Video thumbnail and large preview image

### ISSUE THREAD

**Issue by annabzz** [artpolikarpov/fotorama#431]
Right now, when I have a videogallery I upload an extra image for every video. This way I can use as a thumbnail and as a preview image. The thing is that if I use a small image, it's too small for the preview. But if I use a larger one, it's way too big for the thumbnail. (It's not like they don't fit, I'm concerned about performance)
So, my doubt is: if I use an image twice, does it load once or twice?
Also, is there any way to upload a different image for the preview and another for the thumbnail (they would be the same, but with different quality).
Thanks!

**Comment by ulaharbmg** [comment]
You can use data options thumbnails
```javascript
...
thumb: "thumb_path"
...
```
and data for preview images
```javascript
...
img: "img_path"
...
```
for json data format

**Comment by annabzz** [comment]
ok, thanks!
