### ISSUE TITLE
Initialize in hidden modal

### ISSUE THREAD

**Issue by jangrewe** [artpolikarpov/fotorama#433]
Hi, i'm trying to initialize Fotorama in a Bootstrap 3 modal which will be used with fotorama.load(data) and then shown, so that i can reuse the modal and gallery multiple times on the page.

Unfortunately Fotorama doesn't seem to initialize when the element is hidden, it only works if i show the modal first, close it, initialize Fotorama, load the data, and then show it again.

Could it be fixed so that Fotorama can be initialized in a hidden element, too? Thanks!

**Comment by krtrice** [comment]
I'd love to see this fixed too! Seems to be a possible duplicate of https://github.com/artpolikarpov/fotorama/issues/406

**Comment by jangrewe** [comment]
It is indeed, thanks for the notice. I'll close this one and will follow #406 - thanks again!
