### ISSUE TITLE
how can I link my sldie images to external urls

### ISSUE THREAD

**Issue by metroinkprinting** [artpolikarpov/fotorama#436]
I am trying to figure out how can I link my slide images to external urls.

Can you explain how this can be done?

Thank you for your help.

**Comment by metroinkprinting** [comment]
Is it possible to get a response on this?

**Comment by cipick** [comment]
i suggest using the data-caption attribute.
here's a demo http://jsfiddle.net/ark9x97c/

**Comment by metroinkprinting** [comment]
Is there any way to make the whole slide clickable? Or is it only possible
to do it will a button?

Thanks.


-- 

*Follow us on INSTAGRAM <https://instagram.com/metroink/>*
*Check out our products on YOUTUBE <http://youtube.com/MetroInkLTD>*

***PLEASE TRIPLE CHECK PROOFS BEFORE GIVING FINAL APPROVAL FOR PRINT. ONCE
FINAL APPROVAL IS GIVEN WE ARE NOT RESPONSIBLE FOR ANY ERRORS INCLUDING BUT
NOT LIMITED TO SPELLING, GRAMMATICAL, AND INFORMATIONAL ERRORS***

*Thomas*
*Metroink* - Graphics • Printing • Mailing • Web Sites
Graphic Designer/Web Developer

*www.metroink.com <http://www.metroink.com>*
*Phone:* 718-351-5922 x.204
*Fax:* 718-351-7505
*Hours:*
M-F: 9:30-5:30

DISCLAIMER: This e-mail and any file(s) transmitted with it, is
intended for the exclusive use by the person(s) mentioned above as
recipient(s). This e-mail may contain confidential information and/or
information protected by intellectual property rights or other rights.
If you are not the intended recipient of this e-mail, you are hereby
notified that any dissemination, distribution, copying, or action
taken in relation to the contents of and attachments to this e-mail is
strictly prohibited and may be unlawful. If you have received this
e-mail in error, please notify the sender and delete the original and
any copies of this e-mail and any printouts immediately from your
system and destroy all copies of it.

**Comment by cipick** [comment]
using custom html
here's a demo http://jsfiddle.net/artpolikarpov/8tjrJ/ <http://jsfiddle.net/artpolikarpov/8tjrJ/>
