### ISSUE TITLE
unminified js version

### ISSUE THREAD

**Issue by BackuPs** [artpolikarpov/fotorama#437]
Hi 

is it possible to get the unminified js version 4.6.4 of the script?

js & css

Thank you

**Comment by cipick** [comment]
> Test that Grunt's CLI is installed by running `grunt --version`. If the command isn't found, run `npm install -g grunt-cli`. For more information about installing Grunt, see the getting started guide.

> Fork and clone the repo.
Run `npm install` to install all dependencies (including Grunt).
Run `grunt` to grunt this project.

Get files from `out/futurama.dev.*`

**Comment by flarn2006** [comment]
![](https://www.syfy.com/sites/syfy/files/styles/syfy_cast_detail_smartphone_narrow_1x/public/cast_futurama_proffarnsworth.jpg)
Good news, everyone! I have discovered what appears to be a typo in the previous comment!
