### ISSUE TITLE
Allow relative/unstyled thumbs

### ISSUE THREAD

**Issue by wuuti** [artpolikarpov/fotorama#444]
It would be great if thumbs could be displayed in a non static way. Currently you have to choose one size before init, and it is in px. The width of the thumbs is then added as inline style to the elements - which makes it quite impossible to style thumbnails differently on different devices with media queries.
E.g. I would like to show thumbs on smartphones with a size of "20vw", which results in 5 thumbs displayed in the row at once, without thinking about the concrete pixel device width...

**Comment by q-ber** [comment]
I also encountered this problem. I make the simple plugin which resizes the preview for different screens and devices. Maybe it will help you.
https://github.com/q-ber/fotorama-adaptive-thumbs.git
