### ISSUE TITLE
Lazy load images with srcset

### ISSUE THREAD

**Issue by tyssen** [artpolikarpov/fotorama#447]
Would it be possible to lazy load images that have srcset and sizes attributes? Maybe by adding a data-srcset attribute to the anchor tags?

Also would it be possible to show a count of how many images in a set and your position in them, e.g. 1/10, 2/10 etc.?

**Comment by chiedu-t0m** [comment]
Would be great to get feedback on srcsets and sizes this given fotorama is Magento 2 dependancy on the product page gallery - there is massive demand for this now. srcsets and sizes is not a privilege but a right for web users - still taken back every time i don't see a plugin or CMS using it

**Comment by atakanaydin** [comment]
+1 we need lazy load on img tag please! @artpolikarpov
