### ISSUE TITLE
Link doesn't work in Chrome

### ISSUE THREAD

**Issue by koncha99** [artpolikarpov/fotorama#448]
Hello,

When I click fotorama images that has href attributes in chrome, it sometimes doesn't work.
It seems to be a ploblem related #222 .
Does this problem have not fix yet? ( I know it may be caused by Chrome.)

Thanks,

**Comment by wildproger** [comment]
Sorry. I don't speak and read English. I from Russia:-).

Пользователь Keisuke Kondo <notifications@github.com> писал:

>Hello,WhenIclickfotoramaimagesthathashrefattributesinchrome,itsometimesdoesn'twork.Itseemstobeaploblemrelated#222.Doesthisproblemhavenotfixyet?(IknowitmaybecausedbyChrome.)Thanks,ReplytothisemaildirectlyorviewitonGitHub.

**Comment by Lnx38** [comment]
That should be fix ur problem (place this into document ready):

$(document).on('click', '.your-object', function(event) {
//events
})
