### ISSUE TITLE
Full screen mode - close on click on the dimmed area

### ISSUE THREAD

**Issue by Siton-Systems** [artpolikarpov/fotorama#460]
How to create this ? (like in facebook lightbox and so on).

When you click outside the area you exit (red border area in the screen shot i added)

This is the most famous behavior for exit full-screen mode (Better UI pattern)

![click-to-close](https://cloud.githubusercontent.com/assets/16711871/13379268/a694b76e-de29-11e5-818a-48e651301744.jpg)

**Comment by dimasch** [comment]
Hey, Guys! We found a solution?
