### ISSUE TITLE
Загружать первые слайды, только когда появится в видимой части экрана

### ISSUE THREAD

**Issue by yurikosan** [artpolikarpov/fotorama#464]
Привет. Есть ли такая возможность в фотораме? Позволяет избежать сотен запросов, если на странице много товаров с превьюхами.

**Comment by uharbachou** [comment]
@yurikosan изначально в фотораме грузится минимум 2 слайда, максимум 3
если первая картинка по умолчанию первая или последняя, то 2
если в серединке, то 3
если loop: true то 3

**Comment by yurikosan** [comment]
@uharbachou это справедливо в рамках одного слайдера.
Я же имею в виду случай, когда на экране показан список из 40 товаров в столбик и у каждого есть слайдер с фотками.

**Как сейчас**
Сразу идет загрузка 40 или даже 40*2 первых фотографий (по 1-2 у каждого слайдера)

**Как я хочу**
На 1 скролле экрана видны будут допустип всего 5 товаров. Должны сразу начать грузиться только первые фотографии этих 5 товаров.
Далее, по мере скролла вниз, как только появится товар в видимой части экрана - подгружать его  первые фотографии.

**Comment by yurikosan** [comment]
https://github.com/artpolikarpov/fotorama/pull/468
