### ISSUE TITLE
fotorama plugin not works fine with popup

### ISSUE THREAD

**Issue by smemamian** [artpolikarpov/fotorama#465]
Hi

I would like to use fotorama plugin.

I want to use this plugin in my **index page** and in my **popup page**.

this plugin works fine on two places, but when I open my popup page,thumbs of images on index page will be removed:

see this site:

http://www.shadyab.com/ali/

fotorama on index page work fine:

http://i.stack.imgur.com/6c8a1.jpg

click on eye icon to open new popup:

http://i.stack.imgur.com/WMTp0.jpg

fotorama on popup page work fine but after loaded popup, fotorama on index page will be removed !

http://i.stack.imgur.com/4II3y.jpg

**Comment by uharbachou** [comment]
Hi, @smemamian 
here can be few problems
Please check your config, check your layout, problem can be if it display: none while gallery try to init. Problem not in gallery likely. Problem how you use it. If problem actual, please write uharbachou@gmail.com. I will help you.
