### ISSUE TITLE
gulp-autoprefixer: Replace transition-property

### ISSUE THREAD

**Issue by Leagnus** [artpolikarpov/fotorama#466]
gulp-autoprefixer ругается на transition-property.
Какие последствия, если просто убрать @extend %transition-for-slide?

**Comment by uharbachou** [comment]
@Leagnus 
По-моему проблема в автопрефиксере, посмотрите пожалуйста версию gulp-autoprefixer.
```css
@extend %transition-for-slide
```
отвечает за перебегающий бордер на табнейлах. поэтому либо попробуйте без extend сделать(он используется только в одном месте) либо разбираться с автопрефиксером.
