### ISSUE TITLE
Fotorama: onClick not working on a Surface running Windows 10

### ISSUE THREAD

**Issue by butterperson** [artpolikarpov/fotorama#467]
The title says it all. I attach a function to the Click event, and my debug software tells me that the event is not being triggered. Only on Windows 8 and above. Any ideas?

**Comment by uharbachou** [comment]
@butterperson 
Impossible. It work fine on windows 8/10 and windows phone 10.
Please, make jsfiddle demo.
Thank you.

**Comment by butterperson** [comment]
I am working on a JSFiddle (not my area of knowledge). I can tell you this
from other research: the failure I'm seeing is only on the Microsoft
Surface. The operating system seems not to be a factor.

For what it may be worth, the site in question is using an older version of
fotorama (3.0.6). On the latest version I cannot get an onClick event to
work on any system or hardware.

Thanks for your attention. I will write more after more research.

On Sun, Mar 20, 2016 at 6:11 AM, Ulad <notifications@github.com> wrote:

> @butterperson <https://github.com/butterperson>
> Impossible. It work fine on windows 8/10 and windows phone 10.
> Please, make jsfiddle demo.
> Thank you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/artpolikarpov/fotorama/issues/467#issuecomment-198929110>
>



-- 
DE GUSTIBUS NON EST DISPUTANDUM
