### ISSUE TITLE
Captions shown only when hovered over image?

### ISSUE THREAD

**Issue by bay1992** [artpolikarpov/fotorama#469]
First off thanks a lot for this great image slider, it has been great so far considering my basic knowledge of HTML and non-existent knowledge of java script.

I've got my fotorama just like I want it, _except_ my captions are too distracting so I only want them shown if the mouse is hovering over the image (much like how just like how the arrows and full screen button show only when hovering over the image).

I've attempted to replicate X4's advice here (https://github.com/artpolikarpov/fotorama/issues/168) without any success. Either I am doing it wrong or the code is now out of date. 

Any advice?

**Comment by uharbachou** [comment]
This feature can be added easy only in styles.
