### ISSUE TITLE
Large block when return from full-screen

### ISSUE THREAD

**Issue by ghost** [artpolikarpov/fotorama#472]
Some example:

```
<table style="width: 100%;">
    <tr>
        <td>
            <div class="fotorama" data-width="100%" data-nav="thumbs" data-allowfullscreen="native">
                ... imgs ...
            </div>
        </td>
        <td style="width: 300px"></td>
    </tr>
</table>
```

when page is loaded - displayed well
click to see full size
when we return from the full-screen display mode, the initial screen preview becomes very large

**Comment by uharbachou** [comment]
Is it critical to use gallery inside table?

**Comment by hemsonolev** [comment]
This skeleton of product page. The left side is images, the right - price and so on. price block has fixed width, but the images block depends on the size of the monitor.
