### ISSUE TITLE
Thumbnails and links

### ISSUE THREAD

**Issue by annabzz** [artpolikarpov/fotorama#474]
Is there any way to keep my own thumbnails (smaller pictures) and having links over large images? I want to have thumbnails images smaller than the large ones but still be able to click on large images and open another website.

Thanks!

**Comment by yoime** [comment]
@annabzz you need simple carousel. If it feature for gallery it not impossible. Gallery will be useless, because thumbnails only for image navigation and preview opened when you click on thumb item. If you want click and open another page - i see here conflict behavior.
Can you describe why it need?

**Comment by annabzz** [comment]
@yoime well, I'd like to open another page when I click on the large image, to show another page with more information about it. Would that be difficult to do?
Thanks for the reply.

**Comment by uharbachou** [comment]
@annabzz not so difficult. In two days i can find time to add new events for click on preview. Have time wait for this?

**Comment by yoime** [comment]
@annabzz not so difficult. In two days i can find time to add new events for click on preview. Have time wait for this feature?

**Comment by annabzz** [comment]
@yoime wow, thanks! Take your time, I can wait if I know you plan to do it in a near future.

**Comment by yoime** [comment]
@annabzz Yeah, i can do it

**Comment by uharbachou** [comment]
https://github.com/artpolikarpov/fotorama/issues/328#issuecomment-68435847
