### ISSUE TITLE
Как сделать изображения менее резкими? \ Make a pictures less sharp, less pixelate (example inside)

### ISSUE THREAD

**Issue by nickneustroev** [artpolikarpov/fotorama#476]
Главным образом, это заметно, если смотреть на скрины, на которых есть текст. Например:
![image](https://cloud.githubusercontent.com/assets/7358816/14858929/9f1e8bd6-0caa-11e6-8399-c9a21f78a232.png)
Еще аналогичные примеры, если что, на этой странице http://blog.evercodelab.com/arna-test/
Пробовал подставлять разные настройки отображения картинок отсюда http://fotorama.io/customize/, ничего не помогло.
Буду благодарен за решение вопроса или любые идеи и подсказки.

Mainly you can see that, when using screenshot of screens with text. Example picture is attached. And more example by the link above.
I was trying change params of picture listed here http://fotorama.io/customize/  - it's not helped.

**Comment by uharbachou** [comment]
@nickneustroev Ваша проблема заключается скорее всего в том, что изображения картинок не пропорциональны. Я имею ввиду когда высота картинки в галерее отличается от своего оригинального размера, то все начинает плыть. Фоторама сетает высоту для картинок. Там сетается высота и ширина, самый простой способ для Вас без нужны лезть в js установить для картинок в стилях height и width с !important. height

**Comment by nickneustroev** [comment]
@uharbachou Спасибо за идею, но вроде бы не в этом дело, пропорции верные

**Comment by uharbachou** [comment]
@nickneustroev сделайте пожалуйста jsbin, чтобы можно было посмотреть
есть вероятность того, что размер картинки великоват и сильно уменьшается
