### ISSUE TITLE
fotorama-4.6.4.dev - wrong test for equality due missing signal

### ISSUE THREAD

**Issue by sylvio-ruiz** [artpolikarpov/fotorama#478]
fotorama -4.6.4.dev

around line 1641:`if (touchEnabledFLAG = xWin) {stopEvent(e);}`

fix:`if (touchEnabledFLAG == xWin) {stopEvent(e);}`

**Comment by uharbachou** [comment]
Dev branch 2 years old. Working branch as i see only master.
Thank you.
