### ISSUE TITLE
Loop doesn't work with two images in gallery

### ISSUE THREAD

**Issue by rellect** [artpolikarpov/fotorama#480]
When loop is enabled and the gallery contains only two images, the loop doesn't work.

**Comment by birdkiwi** [comment]
http://fotorama.io/customize/loop/

> Requires three or more images.

**Comment by rellect** [comment]
Hello,
Thanks for replying.
May I ask why loop with 2 images is not possible?
Is it because how the animation works?

Thanks,
Refael

**Comment by birdkiwi** [comment]
Artem too busy/lazy to realize it :)

**Comment by rellect** [comment]
Got it, I can try and take a look, I'm a front-end developer myself, but I
can't find the non-minified code.
Anyway, great script. Thanks

Refael

**Comment by TapakaHoB** [comment]
birdkiwi напишите пожалуйста на мою почту s_tarakanov@mail.ru

**Comment by birdkiwi** [comment]
@TapakaHoB  Зачем? Я не разработчик.

**Comment by TapakaHoB** [comment]
@birdkiwi  по поводу вашей программы-поздравлялки Вконтакте).

**Comment by uharbachou** [comment]
@rellect All transparent. The idea of loop with two images same as without him. You always see first and second image. And it not depends turn it on or not.

@TapakaHoB @birdkiwi  удалите пожалуйста сообщения не по теме.

Спасибо

**Comment by dusttier** [comment]
find e.transition,Md=e.loop&&(zd>2||Sd&&(!Wd||"slide"!==Wd))  and replace zd>2 to zd>1

**Comment by darkwoolf10** [comment]
I am not found this string `e.transition,Md=e.loop&&(zd>2||Sd&&(!Wd||"slide"!==Wd))`.
I'm find `o_loop = opts.loop && (size > 1 || (o_fade && (!o_transition || o_transition !== 'slide')));`
platform - Magento 2.2
