### ISSUE TITLE
Don't work in firefox and chrome

### ISSUE THREAD

**Issue by danielX96** [artpolikarpov/fotorama#484]
**Hello I enjoyed the plug-in but I'm having problems with Firefox and chrome, thumbnails open one on top of the other and the first image (large) does not appear. IE works ok but in firefox and chrome not , it happens from time to time on different pages .**

![bugfot](https://cloud.githubusercontent.com/assets/20525267/16932166/13aeae6c-4d1b-11e6-96cd-df6282358ee4.jpg)

**Thank you**

**Comment by yoime** [comment]
Make jsbin.com please. Right now i can't reproduce it.

**Comment by danielX96** [comment]
Thanks for answering , follows the code it is called an iframe to another page , offline it works correctly in Firefox , but unfortunately when uploading it superimposes the images , thank you


https://jsbin.com/kifuhumaxi/edit?html,output

**Comment by danielX96** [comment]
Thanks for answering , follows the code it is called an iframe to another page , offline it works correctly in Firefox , but unfortunately when uploading it superimposes the images , thank you
https://jsbin.com/cevubokega/edit?html,output

**Comment by VascoGamer** [comment]
@danielX96 hello there, have you tried to load images direct from ajax response?

Thanks,

Vasco
