### ISSUE TITLE
Loop, закрытие полноэкранного режима через API в Mozilla (43v)

### ISSUE THREAD

**Issue by maxkuchin** [artpolikarpov/fotorama#485]
Доброго времени суток.
1) Если миниатюры только 2, не срабатывает loop через data-loop. Есть какое-нибудь решение?
2) Закрытие полноэкранного режима через API 
on(
            'fotorama:fullscreenexit ',
            function (e, fotorama, extra) {
            $(".fotorama__fullscreen-icon").removeClass("min");  
            } 
в Mozilla не срабатывает. 
В логе, при попытке закрыть, он почему-то снова выдает событие на открытие, т.е. fullscreenenter

**Comment by yoime** [comment]
1. Зачем Вам включенный зум, если две картинки? В любом случае поведение будет одинаковое.
2. http://fotorama.io/customize/api/#fotorama.cancelFullScreen()
