### ISSUE TITLE
Fotorama is not working in dynamic pages(AJAX)

### ISSUE THREAD

**Issue by darkthefirst** [artpolikarpov/fotorama#487]
Fotorama dont want work when i am ajax my div

**Comment by uharbachou** [comment]
@darkthefirst Can you give more information about your case?

**Comment by darkthefirst** [comment]
I connect html code from another page. But the fotorama does not work. I can include scritp again, but this is not good.

**Comment by uharbachou** [comment]
@darkthefirst 
```javascript
$('div').fotorama();
```
call it in done of ajax request. May be it can help you?

**Comment by darkthefirst** [comment]
I have tried. This does not work. But in any way, thanks.

>

**Comment by uharbachou** [comment]
Also can be problem that gallery not visible(display: none) while try to init gallery.

**Comment by darkthefirst** [comment]
I fixed it
Need to paste before ajax.
jQuery(document).ready(function($){
});
