### ISSUE TITLE
Fotorama & arcticModal

### ISSUE THREAD

**Issue by Solomon2014** [artpolikarpov/fotorama#489]
Как инициализировать эту галерею в попах [arcticModal](http://arcticlab.ru/arcticmodal/) ?

**Comment by uharbachou** [comment]
http://arcticlab.ru/arcticmodal/#examples
там есть событие на afterOpen, если будет прыгать то beforeOpen и потом проапдейтить( возможно понадобится тк на display:none не проинититься)

**Comment by Solomon2014** [comment]
Да события есть, я это знаю. Мне нужно запустит fotoramу в этом попапе, что и как я должен написать в этом afterOpen?
