### ISSUE TITLE
Dots and thumbnails

### ISSUE THREAD

**Issue by yakupov112** [artpolikarpov/fotorama#494]
Можно ли сделать одновременно точки и миниатюры?

**Comment by bender-r** [comment]
Да. 
К примеру точки отобразить через nav: 'dots', а миниматюры через  API, или наоборот.
Старый пример как вывести миниатюры тут http://jsfiddle.net/artpolikarpov/vCUC2/  . Что б заработало, надо ссылки на css и js файлов фоторамы поправить
