### ISSUE TITLE
Fotorama breaks when wrapped in a position fixed container on Chrome 53

### ISSUE THREAD

**Issue by JustinDrake** [artpolikarpov/fotorama#495]
When scrolling from inside a position fixed container, the fotorama widget completely destroys the layout in Chrome 53. This seems to be a bad bug with Chrome 53. Has anyone been experiencing the same issue?

**Comment by JustinDrake** [comment]
Ok, found the culprit in `fotorama.css`:

.fotorama--hidden,.fotorama__load {
    position: absolute;
    left: -99999px;
    top: -99999px;
    z-index: -1;
}

**Comment by yoime** [comment]
@JustinDrake will check it. thank you

**Comment by yoime** [comment]
@JustinDrake hi,
can you describe why you need gallery in fixed block? i mean that problem can be not in gallery.

Thank you.
