### ISSUE TITLE
Incorrect position of fotorama__thumb-border when 'thumbmargin' param is used

### ISSUE THREAD

**Issue by AntonAL** [artpolikarpov/fotorama#505]
Initialize fotorama with 'thumbmargin' param:

```coffee
$('.product-images').fotorama
    nav: 'thumbs'
    thumbmargin: 5
```

By switching to next images, accumulated position error of `fotorama__thumb-border` will be seen.
For n'th thumbnail, position error will be `n * thumbmargin`.
![incorrect position of fotorama__thumb-border](https://cloud.githubusercontent.com/assets/2064830/21289632/01096a76-c4b3-11e6-80b6-894fc3f54b34.png)

**Comment by LiamKarlMitchell** [comment]
The site im working on uses fotorama version 4.6.4
margin defaults at 2.

I'm not sure if thumbmargin was used but I just added a margin-right: 2px to the thumb nav frames.

```css
.fotorama__nav__frame--thumb {
    margin-right: 2px;
}
```

Would prefer a proper fix, the code that sets the transform on .fotorama__thumb-border needs to be adjusted.

getTranslate does not appear to have options as a parameter but MARGIN and OPTIONS.margins are variables in the scope above but I expect those are just defaults and not the real setting if over-ridden...?


```js
obj.transform = 'translate3d(' + (pos+opts.margin) + 'px,0,0)';
```
