### ISSUE TITLE
no-jquery.html

### ISSUE THREAD

**Issue by xinger** [artpolikarpov/fotorama#510]
Привет!
Скажи, а есть какая-то надежда, что фоторама заведется без jquery?
Я нашел такой файлик test/no-jquery.html и у меня появилась надежда )

**Comment by uharbachou** [comment]
никакой, внутри все завязано на нее. 
Вы смотрели внутрь файла. Я не нашел вообще такого файла.

**Comment by uharbachou** [comment]
@xinger nope, it's jquery plugin.
```
test/no-jquery.html
``` only shows you how it works without jquery. i mean shows errors or warnings in console.
