### ISSUE TITLE
Please provide non-minified version of fotorama.js in npm package.

### ISSUE THREAD

**Issue by decease** [artpolikarpov/fotorama#511]
Please provide non-minified version too.

It's need to use fotorama with webpack. There is problem currently, in case if I turn on Unglify plugin in webpack with enabled option keep_fnames. The problem is webpack keep minified names inside fotorama.js, but minifiy it one more time, so names in fotorama.js became conflicted.

It would be great to have non-minified version. Thank you.

**Comment by tonnyhope** [comment]
This issue was moved to uharbachou/liteGallery#4
