### ISSUE TITLE
All pictures in the folder as a gallery ?

### ISSUE THREAD

**Issue by Krabtus** [artpolikarpov/fotorama#513]
Is it possible to tell Fotorama that there are photos in a particular folder, so the complete content is displayed as a gallery? I use Joomla.

I imagine this is similar. . .  ;-)
```
<div class="fotorama"
     data-nav="thumbs">
  <img src="images/gallery">
</div>
```
In the original code, I unfortunately have to assign each picture individually.
```
<div class="fotorama"
     data-nav="thumbs">
  <img src="1.jpg">
  <img src="2.jpg">
</div>
```

**Comment by uharbachou** [comment]
@Krabtus this is javascript. you can transform that on backend. I'm create list of images.
