### ISSUE TITLE
Добавление трёх разных размеров изображения

### ISSUE THREAD

**Issue by mumus** [artpolikarpov/fotorama#514]
Добрый день, возможно ли добавить 3 разних изображения для фоторамы?
1. Для просмотра в обычном режиме, например фото шириной 640 пикселей
2. Для превьюшек, например 160 пикселей
3. И большая 1280 при клике на весь экран?

Пробовал сделать по примерам, но не работает оно.
`<a href="preview_big.jpg" data-full="big_image.jpg" class="gallery__thumb" data-caption="description">
     <img src="preview_thumb.jpg"/>
 </a>`

**Comment by uharbachou** [comment]
@mumus 
```html
<a href="" data-thumb="" data-full=""></a>
```
Без image внутри.

**Comment by mumus** [comment]
Большое спасибо, а как сделать, чтобы когда открывается full картинка, не происходило такого, что показывается сначала обычная, а потом резко на весь экран большая (т.е она еще не успевает загрузится)

**Comment by uharbachou** [comment]
это уже в либе проблема
https://github.com/uharbachou/liteGallery/issues
выписывайте issue с expected result.

как альтернативный вариант показывать прелоадер если картинка не прогрузилась
