### ISSUE TITLE
Zoom buttons don't work

### ISSUE THREAD

**Issue by thdoan** [artpolikarpov/fotorama#515]
Steps to reproduce:

1. Go here: http://magento2-demo.nexcess.net/caesar-warm-up-pant.html
2. Click on image to open zoom overlay
3. Click [+] and [-] buttons to zoom in/out

Clicking [+] and [-] should zoom the image in and out, respectively, but it does nothing.

I can quickly fix this issue by binding the click event to the buttons, but I was not able to find API methods to zoom in/out. Please advise.

**Comment by uharbachou** [comment]
Hi, 
it's not fotorama feature. Find in magento rep. Also here without zoom widget.

Thanks

**Comment by uharbachou** [comment]
And again init of widget library in magento xml configuration. Where true false for turn turn on/turn off functionality. 

Thanks
