### ISSUE TITLE
Enhancement idea: change arrows, change arrow position next to the picture

### ISSUE THREAD

**Issue by Sonnenbad** [artpolikarpov/fotorama#516]
Is there a possibility to change the arrows (bigger and color) and to change arrow position next to the picture (like in fullscreen).
Thanks for your work
Sonnenbad

**Comment by uharbachou** [comment]
Please, clarify what do you mean ?

Thanks

**Comment by Sonnenbad** [comment]
Like here:
![fotorama-arrow](https://cloud.githubusercontent.com/assets/26593940/24240087/b1ee5b7e-0fb0-11e7-9764-9ea38cd6825d.jpg)
Moving the arrow next to the slideshow. And changing the original arrow with an own grafic. For example: a bigger black arrow in a circle.
