### ISSUE TITLE
How to set custom width to Fotorama Nav Shaft?

### ISSUE THREAD

**Issue by alvinofori** [artpolikarpov/fotorama#521]
I have 12 thumbnails, but want to show only 7 of them at a time. When a user switches the images and that blue indicator that shows which thumbnail is showing at that moment gets to the 7th thumbnail, which is the endge of the block, it should normally scroll out the rest of the thumbnails, but it doesn't. On mobile version I need to show only 2 thumbnails out of 12 and should do the same trick. 

This happens when I set the width to the fotorama_nav_shaft, the images don't scroll out at all. What happens is that, the blue indicator goes inside the fotorama_nav_shaft block and you can't see it anymore, the thumbnails don't scroll too.

So the question is, how to make that thumbnail holder responsive or custom width assigned in a way, that i will get 7 thumbnails on desktop, and mobile 2 thumbnails with working scrolling thumbnails?

And yes, fotorama is a unique slider. Thanks!

**Comment by Nivicious** [comment]
@alvinofori did you find a resolution for this? 
Currently hitting the same issue!

**Comment by templatetuners** [comment]
I am also looking to have more than 1 active image
