### ISSUE TITLE
copied example page not working :)

### ISSUE THREAD

**Issue by akasei** [artpolikarpov/fotorama#524]
original site: http://fotorama.io/examples/basic.html
copied source code: https://gresopalety.pl/test.php

why?

**Comment by pkrvs** [comment]
try to connect jquery before </body>

**Comment by istonny** [comment]
Mixed Content: The page at
cant download css and js. All working. Please, see sometimes debug tool

**Comment by akasei** [comment]
Yep, downloaded all files to local disk, now it works.
