### ISSUE TITLE
Fotorama конфликтует с uglify

### ISSUE THREAD

**Issue by dotio** [artpolikarpov/fotorama#528]
При подключении конфликтует с uglify. Пофиксить смог только путем отключения uglify из проекта.

**Comment by igoradamenko** [comment]
Столкнулся с той же проблемой.

Склонировал репу, собрал сам файлы и использую в проекте неминифицированную версию. Тогда Uglify сжимает нормально и ничего не портит.

Возможно вам тоже как-то поможет.
