### ISSUE TITLE
Как не растягивать изображения в Fullscreen?

### ISSUE THREAD

**Issue by kaiwas** [artpolikarpov/fotorama#533]
Здравствуйте!

Как реализовать?
Помимо % и px возможны ли иные варианты?
Хотелось бы чтобы мелкие картинки отображались "как есть" без привязки к %экрана или строгому значению в пикселях.

Хотелось бы что-то вроде width: auto;height: auto;  ну и т.д.
Если прибивать через стили или классы - то скрипт их "устраняет".

Простите, если ответ уже есть и я его не заметил. Честно искал.
Пока это единственная преграда не позволяющая слезть с fancybox.

Заранее спасибо! Ну и благодарствую за труды в общем!

**Comment by artpolikarpov** [comment]
Чтобы картинки не растягивались больше своих физических размеров:
```
data-fit="scaledown"
```

https://fotorama.io/docs/4/fit/
