### ISSUE TITLE
Good news! Fotorama is back!

### ISSUE THREAD

**Issue by gosteev** [artpolikarpov/fotorama#537]
Good news! Fotorama is back!

Thanks to [Uploadcare](https://uploadcare.com/), this project is maintained again!

The plan is simple:
  1. I'll continue where I quit. I’ll try to fix all known issues with v4. I want to be a friend for the army of Fotorama users (≈148,685 live sites worldwide).
  2. After that, I’ll start to work on v5. I’m not going to rewrite the whole thing from scratch. It will be an evolution, not a revolution. Feature requests are welcome!

_Originally posted by @artpolikarpov in https://github.com/artpolikarpov/fotorama/issues/532#issuecomment-456751742_

===

i'll take the liberty to create new issue with requests.
what i want to ask - can we get rid of BEM in future versions of fotorama? it's not the type of methodology that should be used in libraries

**Comment by renofizaldy** [comment]
Finally !! Someone taking care on this

**Comment by VascoGamer** [comment]
Looking forward to see good news :)

My main issue is: how to load dynamic images, and re-create fotorama everytime I click in a link?

Thanks!

**Comment by demon101** [comment]
cool!
