### ISSUE TITLE
navwidth for vertical thumbnails

### ISSUE THREAD

**Issue by banha-serhii** [artpolikarpov/fotorama#545]
How can i use Navigation container for vertical thumbnails?
Because at this moment, that's don't work.
Maybe exist some solution for displaying less elements in vartical navigation thumbnails without change main picture size?

**Comment by artpolikarpov** [comment]
Vertical navigation was in version 3, in version 4 - only horizontal navigation remained. So I'm afraid I won't be able to answer your question.
