### ISSUE TITLE
Load Images into bootstrap modal

### ISSUE THREAD

**Issue by VascoGamer** [artpolikarpov/fotorama#548]
Hello everyone,

Can someone please tell me how do I load dynamic images through ajax?

I have tried a couple to example found on the internet but no success so far.

I really like fotorama it's great, but how can I load it in bootstrap modal for dynamic images?

Appreciate any help.

Kind regards,

Vasco

**Comment by artpolikarpov** [comment]
No one seems ready to answer that question. I have no experience with the Botstrap myself. I hope you have already coped with this.
