### ISSUE TITLE
Fullscreen Mode + Fit = Cover

### ISSUE THREAD

**Issue by ghost** [artpolikarpov/fotorama#64]
Hi,

Issue:
When specifiying data-fit="cover", the images in fullscreen mode are also shown in "cover"-mode, instead of fitting to the visible browser window.

Desired behavior:
Show Fotorama in "cover"-mode, fullscreen in "contain"-mode.

Code:
div class="fotorama" data-width="300" data-ratio="1/1" data-max-width="100%" data-allow-full-screen="native" data-fit="cover"

Thx!

**Comment by malikmalhan** [comment]
Is this bug solved? i think i have same issue when entering fullscreen

Image doesn't update to fit the default container

http://preview-smart3.seat.it/sitepreview/19E54790-ABC8-F4B3-E050-A8C08D264EAF/packaging-e-imballaggi.html
