### ISSUE TITLE
data-nav-position with dots inside the fotorama container

### ISSUE THREAD

**Issue by martin-rohwedder** [artpolikarpov/fotorama#65]
Is it possible to put the small dots or thumbnails inside the fotorama container.

As it is now I only have the opportunity to put dots and thumbnails to the top, bottom, left and right, but outside the container using data-nav-position attribute.

It would be nice to have the feature to use

```
<div class="fotorama" data-nav-position="bottom" data-nav-inside="true">
    <img src="img.jpg" />
    ...
</div>
```

to let the dots get inside the container. Will it be something that you will make soon, since I actually needs it :)

**Comment by prakashbhusal** [comment]
Hello,
I have to enable both thumbnail and dots in the slider. Is this possible?
